language: minimal

sudo: false

before_install:
  # Install and configure miniconda.
  - |
    wget http://bit.ly/miniconda -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda --quiet
    conda config --add channels conda-forge --force
    conda install pycryptosat
    conda config --set channel_priority strict

install:
  # Create the test env.
  - |
    conda env create --file environment.yml --name TEST
    conda install --name TEST --channel conda-forge nbval pytest
    source activate TEST

  # Debug.
  - conda info --all
  - conda list

script:
  # The option `--nbval-lax` won't compare the notebooks cell results,
  # it will only run them! Use `--nbval` instead if you wish to validate outputs.
  - pytest --nbval-lax -p no:python .
